#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS_DIR="${ROOT_DIR}/scripts"
DOMAIN_DIR="${SCRIPTS_DIR}/checks/domain"
FIXTURES_DIR="${ROOT_DIR}/tests/fixtures"
PASS=0
FAIL=0
LAST_OUTPUT=""
LAST_EXIT=0

setup() {
  TMP="$(mktemp -d)"
  mkdir -p "$TMP/.github/workflows" "$TMP/bin"
}

teardown() {
  rm -rf "$TMP"
}

assert_exit() {
  local description="$1"
  local expected="$2"
  local actual="$3"
  if [[ "$actual" -eq "$expected" ]]; then
    echo "  ✅ $description"
    PASS=$((PASS + 1))
  else
    echo "  ❌ $description (expected exit $expected, got $actual)"
    FAIL=$((FAIL + 1))
  fi
}

assert_output_contains() {
  local description="$1"
  local expected="$2"
  if [[ "$LAST_OUTPUT" == *"$expected"* ]]; then
    echo "  ✅ $description"
    PASS=$((PASS + 1))
  else
    echo "  ❌ $description (missing '$expected')"
    FAIL=$((FAIL + 1))
  fi
}

assert_output_not_contains() {
  local description="$1"
  local unexpected="$2"
  if [[ "$LAST_OUTPUT" != *"$unexpected"* ]]; then
    echo "  ✅ $description"
    PASS=$((PASS + 1))
  else
    echo "  ❌ $description (unexpected '$unexpected')"
    FAIL=$((FAIL + 1))
  fi
}

assert_output_count() {
  local description="$1"
  local expected="$2"
  local count="$3"
  local actual
  actual="$(python3 -c 'import sys; print(sys.stdin.read().count(sys.argv[1]))' "$expected" <<<"$LAST_OUTPUT")"
  if [[ "$actual" -eq "$count" ]]; then
    echo "  ??? $description"
    PASS=$((PASS + 1))
  else
    echo "  ??? $description (expected $count occurrence(s) of '$expected', got $actual)"
    FAIL=$((FAIL + 1))
  fi
}

assert_json_duration_seconds() {
  local description="$1"
  local json_path="$2"
  if python3 -c '
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
v = d.get("duration_seconds")
assert isinstance(v, int) and not isinstance(v, bool), type(v)
assert v >= 0
' "$json_path"; then
    echo "  ??? $description"
    PASS=$((PASS + 1))
  else
    echo "  ??? $description (duration_seconds missing or not an integer >= 0)"
    FAIL=$((FAIL + 1))
  fi
}

assert_aggregate_critical_scope_order() {
  local description="$1"
  if printf '%s' "$LAST_OUTPUT" | python3 -c '
import sys
s = sys.stdin.read()
assert "#### Critical" in s, "missing Critical section"
start = s.index("#### Critical")
end = s.find("#### High", start)
block = s[start:end] if end != -1 else s[start:]
assert "##### Code" in block and "##### Settings" in block
c = block.index("##### Code")
st = block.index("##### Settings")
line7 = "- **CICD-SEC-07-RUNNER-HARDENING**"
line1 = "- **CICD-SEC-01-FLOW**"
assert line7 in block and line1 in block
off7 = block.index(line7)
off1 = block.index(line1)
assert c < off7 < st < off1, (c, off7, st, off1)
'; then
    echo "  ✅ $description"
    PASS=$((PASS + 1))
  else
    echo "  ❌ $description (Critical section Code/Settings order or check_id placement)"
    FAIL=$((FAIL + 1))
  fi
}

run_check() {
  local script="$1"
  shift
  local output_file
  output_file="$(mktemp)"
  set +e
  bash "$script" "$@" >"$output_file" 2>&1
  LAST_EXIT=$?
  set -e
  LAST_OUTPUT="$(python3 - <<'PY' "$output_file"
import pathlib, sys
print(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace"))
PY
)"
  rm -f "$output_file"
}

write_guardrails_yml() {
  local target_dir="$1"
  local mode="$2"
  local check_id="$3"
  local registry="${4:-public}"
  cat > "$target_dir/.guardrails.yml" <<EOF
context:
  visibility: public
  software_type: open_source
  runner_type: github_hosted
  container_registry: ${registry}
  data_sensitivity: medium
  deployment_criticality: dev
checks:
  ${check_id}:
    mode: ${mode}
EOF
}

write_empty_npm_lock() {
  cat >"$1" <<'EOF'
{"name":"fixture","version":"1.0.0","lockfileVersion":3,"requires":true,"packages":{"":{"name":"fixture","version":"1.0.0"}}}
EOF
}

write_empty_yarn_lock() {
  cat >"$1" <<'EOF'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
EOF
}

write_empty_pnpm_lock() {
  cat >"$1" <<'EOF'
lockfileVersion: '9.0'
importers:
  .: {}
packages: {}
snapshots: {}
EOF
}

echo ""
echo "▶ cicd_sec_04_poisoned_pipeline.sh"
setup
cp "$FIXTURES_DIR/bad-prt.yml" "$TMP/.github/workflows/ci.yml"
run_check "$DOMAIN_DIR/cicd_sec_04_poisoned_pipeline.sh" "$TMP"
assert_exit "detects pull_request_target usage" 1 "$LAST_EXIT"
assert_output_contains "includes Searched block" "### Searched"
assert_output_contains "includes Scan coverage block" "### Scan coverage"
assert_output_contains "includes Found block" "### Found"
assert_output_contains "includes Remediation block" "### Remediation"
assert_output_contains "renders Mode line" "Mode: **fail**"
assert_output_contains "renders Duration line" "Duration: **"
assert_output_contains "emits coarse start phase" "phase: start"
teardown

echo ""
echo "▶ result JSON includes duration_seconds"
setup
cp "$FIXTURES_DIR/bad-prt.yml" "$TMP/.github/workflows/ci.yml"
mkdir -p "$TMP/results"
export GUARDRAILS_RESULT_DIR="$TMP/results"
run_check "$DOMAIN_DIR/cicd_sec_04_poisoned_pipeline.sh" "$TMP"
unset GUARDRAILS_RESULT_DIR
assert_exit "check still fails with result dir set" 1 "$LAST_EXIT"
assert_json_duration_seconds "JSON duration_seconds is integer >= 0" \
  "$TMP/results/CICD-SEC-04-POISONED-PIPELINE.json"
teardown

echo ""
echo "▶ cicd_sec_08_action_pinning.sh"
setup
mkdir -p "$TMP/actions/sample"
cp "$FIXTURES_DIR/bad-pinning.yml" "$TMP/actions/sample/action.yml"
run_check "$DOMAIN_DIR/cicd_sec_08_action_pinning.sh" "$TMP"
assert_exit "detects unpinned action references in composite action" 1 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_05_permissions.sh"
setup
cp "$FIXTURES_DIR/good-workflow.yml" "$TMP/.github/workflows/ci.yml"
run_check "$DOMAIN_DIR/cicd_sec_05_permissions.sh" "$TMP"
assert_exit "passes for valid permissions blocks" 0 "$LAST_EXIT"
assert_output_contains "uses CICD-SEC-05-PERMISSIONS designation" "CICD-SEC-05-PERMISSIONS"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh"
setup
echo '{"name":"demo"}' > "$TMP/package.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when npm lockfile is missing" 1 "$LAST_EXIT"
assert_output_contains "SEC-03 phase inventory" "phase: inventory"
assert_output_contains "SEC-03 phase python" "phase: python"
assert_output_contains "SEC-03 phase js" "phase: js"
assert_output_contains "SEC-03 phase lockfiles" "phase: lockfiles"
assert_output_contains "SEC-03 phase workflows" "phase: workflows"
assert_output_contains "SEC-03 phase docker" "phase: docker"
assert_output_contains "SEC-03 phase summary" "phase: summary"
assert_output_contains "SEC-03 skips Go checker without go.mod inventory trigger" "Go ecosystems.yml policy: skipped; no configured detection files (go.mod) found in inventory."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh reports unsupported Maven without failing"
setup
cat >"$TMP/pom.xml" <<'EOF'
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>demo</artifactId>
  <version>1.0.0</version>
</project>
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when only an unsupported pom.xml is present" 0 "$LAST_EXIT"
assert_output_contains "reports Maven as an unsupported dependency signal" "Unsupported Maven dependency signal 'pom.xml' detected"
assert_output_contains "records the unsupported signal as a notice" "[notice] pom.xml"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh accepts configured TypeScript and JavaScript projects"
setup
mkdir -p "$TMP/ts-green" "$TMP/js-green"
echo '{}' >"$TMP/ts-green/tsconfig.json"
echo '{"name":"ts-green","private":true}' >"$TMP/ts-green/package.json"
write_empty_npm_lock "$TMP/ts-green/package-lock.json"
echo '{}' >"$TMP/js-green/jsconfig.json"
echo '{"name":"js-green","private":true}' >"$TMP/js-green/package.json"
write_empty_yarn_lock "$TMP/js-green/yarn.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes exact tsconfig/jsconfig projects with package.json and one lockfile" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh keeps Bun in JavaScript policy"
setup
echo '{"name":"bun-app","private":true}' >"$TMP/package.json"
printf 'BUNLOCK' >"$TMP/bun.lockb"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes package.json with a nonempty bun.lockb" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh ignores specialized compiler config filenames"
setup
echo '{}' >"$TMP/tsconfig.app.json"
echo '{}' >"$TMP/jsconfig.build.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when only non-exact tsconfig/jsconfig variants exist" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh rejects lone TypeScript and JavaScript project configs"
setup
mkdir -p "$TMP/ts-red" "$TMP/js-red"
echo '{}' >"$TMP/ts-red/tsconfig.json"
echo '{}' >"$TMP/js-red/jsconfig.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when exact tsconfig/jsconfig projects lack package.json" 1 "$LAST_EXIT"
assert_output_contains "reports lone tsconfig.json" "ts-red/tsconfig.json"
assert_output_contains "reports lone jsconfig.json" "js-red/jsconfig.json"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh rejects ambiguous JavaScript trigger sets"
setup
echo '{}' >"$TMP/tsconfig.json"
echo '{}' >"$TMP/jsconfig.json"
echo '{"name":"ambiguous","private":true}' >"$TMP/package.json"
write_empty_npm_lock "$TMP/package-lock.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when tsconfig.json and jsconfig.json share one package directory" 1 "$LAST_EXIT"
assert_output_contains "reports ambiguous JavaScript/TypeScript triggers" "Ambiguous JavaScript/TypeScript project triggers"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh audits config and package.json directories once"
setup
echo '{}' >"$TMP/tsconfig.json"
echo '{"name":"typed","private":true}' >"$TMP/package.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when a configured TypeScript project lacks a lockfile" 1 "$LAST_EXIT"
assert_output_count "reports one missing-lock finding for tsconfig beside package.json" "JavaScript project is missing a lockfile" 2
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh ignores uses: in workflow prose"
setup
mkdir -p "$TMP/.github/workflows"
cp "$FIXTURES_DIR/workflow-prose-uses.yml" "$TMP/.github/workflows/prose.yml"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when only prose contains uses:" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh scopes workflow YAML discovery"
setup
cp "$FIXTURES_DIR/bad-pinning.yml" "$TMP/application.yml"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "ignores non-workflow YAML during action pin audit" 0 "$LAST_EXIT"
assert_output_contains "reports no workflow YAML outside .github/workflows" "Workflow YAML for third-party action pins: 0 files"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh validation_skip_paths (requires yq)"
if command -v yq >/dev/null 2>&1; then
  setup
  mkdir -p "$TMP/vendor/nested" "$TMP/apps/web"
  echo '{"name":"v"}' >"$TMP/vendor/nested/package.json"
  echo '{}' >"$TMP/vendor/nested/package-lock.json"
  echo '{"name":"w"}' >"$TMP/apps/web/package.json"
  write_empty_yarn_lock "$TMP/apps/web/yarn.lock"
  cat >"$TMP/.guardrails.file-patterns.yml" <<'EOF'
version: 1
validation_skip_paths:
  - "vendor/*"
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "passes when vendor tree skipped and app has lockfile" 0 "$LAST_EXIT"
  teardown
else
  echo "  (skipped: yq not installed)"
fi

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh monorepo with mixed services"
setup
mkdir -p "$TMP/services/api" "$TMP/services/worker"
cat > "$TMP/services/api/package.json" <<'EOF'
{"name":"api","private":true}
EOF
cat > "$TMP/services/worker/package.json" <<'EOF'
{"name":"worker","private":true}
EOF
write_empty_npm_lock "$TMP/services/worker/package-lock.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when one nested package.json misses lockfile" 1 "$LAST_EXIT"
assert_output_contains "reports nested path for missing lockfile" "services/api/package.json"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh passes for locked js monorepo"
setup
mkdir -p "$TMP/apps/web" "$TMP/apps/docs"
cat > "$TMP/apps/web/package.json" <<'EOF'
{"name":"web","private":true}
EOF
write_empty_yarn_lock "$TMP/apps/web/yarn.lock"
cat > "$TMP/apps/docs/package.json" <<'EOF'
{"name":"docs","private":true}
EOF
write_empty_pnpm_lock "$TMP/apps/docs/pnpm-lock.yaml"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when nested npm manifests have lockfiles" 0 "$LAST_EXIT"
assert_output_contains "includes Scan coverage for manifests" "### Scan coverage"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh validates npm, Yarn Classic, Yarn Berry, and pnpm"
setup
mkdir -p "$TMP/npm" "$TMP/yarn-classic" "$TMP/yarn-berry" "$TMP/pnpm"
for project in npm yarn-classic yarn-berry pnpm; do
  cat >"$TMP/$project/package.json" <<EOF
{"name":"$project","private":true,"dependencies":{"lodash":"4.17.21"}}
EOF
done
cat >"$TMP/npm/package-lock.json" <<'EOF'
{"name":"npm","version":"1.0.0","lockfileVersion":3,"packages":{"":{"name":"npm","version":"1.0.0","dependencies":{"lodash":"4.17.21"}},"node_modules/lodash":{"version":"4.17.21","resolved":"https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz","integrity":"sha512-AAAA"}}}
EOF
cat >"$TMP/yarn-classic/yarn.lock" <<'EOF'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-AAAA
EOF
cat >"$TMP/yarn-berry/yarn.lock" <<'EOF'
__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/aaaaaaaa
  languageName: node
  linkType: hard
EOF
cat >"$TMP/pnpm/pnpm-lock.yaml" <<'EOF'
lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      lodash:
        specifier: 4.17.21
        version: 4.17.21
packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-AAAA}
snapshots:
  lodash@4.17.21: {}
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes all supported JavaScript lockfile formats" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh rejects JavaScript ranges and mutable URLs"
setup
mkdir -p "$TMP/range" "$TMP/url"
echo '{"name":"range","dependencies":{"left-pad":"^1.3.0"}}' >"$TMP/range/package.json"
write_empty_npm_lock "$TMP/range/package-lock.json"
echo '{"name":"url","devDependencies":{"tool":"git+https://example.com/tool.git#main"}}' >"$TMP/url/package.json"
write_empty_npm_lock "$TMP/url/package-lock.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails for a SemVer range and Git dependency without commit SHA" 1 "$LAST_EXIT"
assert_output_contains "reports ranged JavaScript dependency" "left-pad"
assert_output_contains "reports mutable Git dependency" "tool"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh requires exactly one JavaScript lockfile family"
setup
echo '{"name":"multiple","private":true}' >"$TMP/package.json"
write_empty_npm_lock "$TMP/package-lock.json"
write_empty_yarn_lock "$TMP/yarn.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when two lockfile families coexist" 1 "$LAST_EXIT"
assert_output_contains "reports multiple lockfile families" "multiple lockfile families"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh ignores manifests in generated directories"
setup
mkdir -p "$TMP/frontend/.next/dev" "$TMP/frontend/coverage" "$TMP/frontend/.turbo"
echo '{"name":"next-build-artifact","dependencies":{"lodash":"4.17.21"}}' >"$TMP/frontend/.next/dev/package.json"
echo '{"name":"coverage-artifact"}' >"$TMP/frontend/coverage/package.json"
echo '{"name":"turbo-artifact"}' >"$TMP/frontend/.turbo/package.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when only generated directories contain package.json" 0 "$LAST_EXIT"
echo '{"name":"real-app","private":true}' >"$TMP/frontend/package.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "still fails for a real package.json outside generated directories" 1 "$LAST_EXIT"
assert_output_contains "reports the real project as missing a lockfile" "frontend/package.json"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh rejects missing lock integrity"
setup
echo '{"name":"bad-integrity","dependencies":{"lodash":"4.17.21"}}' >"$TMP/package.json"
cat >"$TMP/package-lock.json" <<'EOF'
{"name":"bad-integrity","version":"1.0.0","lockfileVersion":3,"packages":{"":{"name":"bad-integrity","version":"1.0.0"},"node_modules/lodash":{"version":"4.17.21","resolved":"https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"}}}
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when npm lock entry has no integrity" 1 "$LAST_EXIT"
assert_output_contains "reports missing npm integrity" "lacks valid integrity evidence"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh permits peers and immutable JavaScript specs"
setup
cat >"$TMP/package.json" <<'EOF'
{
  "name": "allowed-specs",
  "dependencies": {
    "exact": "=1.2.3",
    "prerelease": "2.0.0-rc.1",
    "local-file": "file:../local-file",
    "local-link": "link:../local-link",
    "workspace-lib": "workspace:*",
    "alias": "npm:lodash@4.17.21",
    "git-pinned": "git+https://example.com/repo.git#0123456789abcdef0123456789abcdef01234567"
  },
  "peerDependencies": {
    "react": "^18.0.0"
  }
}
EOF
write_empty_npm_lock "$TMP/package-lock.json"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes allowed immutable specs and ranged peerDependencies" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for python pyproject without lockfile"
setup
mkdir -p "$TMP/services/py"
cat > "$TMP/services/py/pyproject.toml" <<'EOF'
[project]
name = "py-service"
version = "0.1.0"
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when pyproject has no satisfier lockfile" 1 "$LAST_EXIT"
assert_output_contains "reports missing python satisfier" "missing a required lock or hashed requirements"
assert_output_contains "Python-only repo skips JavaScript" "JavaScript/TypeScript ecosystems.yml policy: skipped"
assert_output_contains "Python-only repo skips Dart" "Dart ecosystems.yml policy: skipped"
assert_output_contains "Python-only repo skips Rust" "Rust ecosystems.yml policy: skipped"
assert_output_contains "Python-only repo skips Ruby" "Ruby ecosystems.yml policy: skipped"
assert_output_contains "Python-only repo skips PHP" "PHP ecosystems.yml policy: skipped"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for unpinned python requirements"
setup
mkdir -p "$TMP/services/py"
cat > "$TMP/services/py/requirements.txt" <<'EOF'
requests
flask==3.0.3
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails for non pinned requirements entry" 1 "$LAST_EXIT"
assert_output_contains "reports unpinned dependency name" "Unpinned python dependency 'requests'."
assert_output_contains "reports unpinned dependency with line number" "requirements.txt:1"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh deduplicates remediation bullets"
setup
mkdir -p "$TMP/services/py"
cat > "$TMP/services/py/requirements.txt" <<'EOF'
requests
flask
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails for multiple unpinned requirements" 1 "$LAST_EXIT"
remediation_count="$(printf '%s' "$LAST_OUTPUT" | awk '
  /^### Remediation$/ { in_rem=1; next }
  in_rem && /^### / { in_rem=0 }
  in_rem && /^## / { in_rem=0 }
  in_rem && /^- Pin each dependency with exact ==/ { c++ }
  END { print c+0 }
')"
if [[ "$remediation_count" -eq 1 ]]; then
  echo "  ✅ remediation lists shared fix once"
  PASS=$((PASS + 1))
else
  echo "  ❌ remediation lists shared fix once (expected 1 bullet, got $remediation_count)"
  FAIL=$((FAIL + 1))
fi
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh passes for pinned python dependencies"
setup
mkdir -p "$TMP/services/py"
cat > "$TMP/services/py/pyproject.toml" <<'EOF'
[project]
name = "py-service"
version = "0.1.0"
EOF
cat > "$TMP/services/py/poetry.lock" <<'EOF'
[metadata]
lock-version = "2.0"
content-hash = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

[[package]]
name = "pytest"
version = "8.3.2"
files = [
    {file = "pytest-8.3.2-py3-none-any.whl", hash = "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"},
]
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes for pyproject with valid poetry.lock hashes" 0 "$LAST_EXIT"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for ambiguous python triggers"
setup
mkdir -p "$TMP/services/py"
cat > "$TMP/services/py/pyproject.toml" <<'EOF'
[project]
name = "py-service"
version = "0.1.0"
EOF
echo "requests" > "$TMP/services/py/requirements.in"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails for disallowed multi-trigger set" 1 "$LAST_EXIT"
assert_output_contains "reports ambiguous python triggers" "Ambiguous Python dependency triggers"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh discovers files under scan_repo checkout path (CI layout)"
setup
mkdir -p "$TMP/scan_repo/.github/workflows"
cat > "$TMP/scan_repo/requirements.txt" <<'EOF'
fastapi
EOF
cp "$FIXTURES_DIR/good-workflow.yml" "$TMP/scan_repo/.github/workflows/ci.yml"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP/scan_repo"
assert_exit "fails for unpinned requirements under scan_repo path" 1 "$LAST_EXIT"
assert_output_contains "finds python package_policy under scan_repo path" "Python package_policy: 1 director"
assert_output_contains "evaluates workflow under scan_repo path" "Workflow YAML for third-party action pins: 1 files"
assert_output_contains "reports unpinned python dependency under scan_repo path" "Unpinned python dependency"
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for missing go lockfile"
setup
mkdir -p "$TMP/services/go-api"
cat > "$TMP/services/go-api/go.mod" <<'EOF'
module example.com/go-api

go 1.22
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when go.mod has no go.sum" 1 "$LAST_EXIT"
assert_output_contains "reports missing go lockfile" "Missing go.sum next to go.mod."
assert_output_contains "reports Go remediation loaded from YAML" "Run go mod tidy and commit go.sum."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh validates Go ecosystems.yml rules"
setup
mkdir -p "$TMP/services/go-api"
cat >"$TMP/services/go-api/go.mod" <<'EOF'
module example.com/go-api

go 1.22
EOF
printf 'example.com/dependency v1.0.0 h1:AAAA\n' >"$TMP/services/go-api/go.sum"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when go.mod has a nonempty same-directory go.sum" 0 "$LAST_EXIT"
printf '' >"$TMP/services/go-api/go.sum"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when go.sum is empty" 1 "$LAST_EXIT"
assert_output_contains "preserves empty go.sum finding" "go.sum is empty."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh skips orphan go.sum without go.mod"
setup
mkdir -p "$TMP/services/not-a-go-project"
printf '' >"$TMP/services/not-a-go-project/go.sum"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes without a go.mod detection file" 0 "$LAST_EXIT"
assert_output_contains "records skipped Go audit" "Go ecosystems.yml policy: skipped; no configured detection files (go.mod) found in inventory."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh validates Dart ecosystems.yml rules"
setup
mkdir -p "$TMP/services/dart-app"
cat >"$TMP/services/dart-app/pubspec.yaml" <<'EOF'
name: dart_app
environment:
  sdk: ">=3.0.0 <4.0.0"
EOF
printf 'packages:\n' >"$TMP/services/dart-app/pubspec.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes when pubspec.lock contains the packages marker" 0 "$LAST_EXIT"
printf '# TODO\n' >"$TMP/services/dart-app/pubspec.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when nonempty pubspec.lock lacks packages marker" 1 "$LAST_EXIT"
assert_output_contains "reports missing Dart packages section" "pubspec.lock is missing the packages section."
printf '' >"$TMP/services/dart-app/pubspec.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when pubspec.lock is empty" 1 "$LAST_EXIT"
assert_output_contains "reports empty Dart lockfile" "pubspec.lock is empty."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for missing Dart lockfile"
setup
mkdir -p "$TMP/services/dart-app"
printf 'name: dart_app\n' >"$TMP/services/dart-app/pubspec.yaml"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when pubspec.yaml has no pubspec.lock" 1 "$LAST_EXIT"
assert_output_contains "reports missing Dart lockfile" "Missing pubspec.lock next to pubspec.yaml."
assert_output_contains "reports Dart remediation loaded from YAML" "Run dart pub get or flutter pub get and commit pubspec.lock."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh skips orphan pubspec.lock"
setup
mkdir -p "$TMP/services/not-a-dart-project"
printf '' >"$TMP/services/not-a-dart-project/pubspec.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "passes without a pubspec.yaml detection file" 0 "$LAST_EXIT"
assert_output_contains "records skipped Dart audit" "Dart ecosystems.yml policy: skipped; no configured detection files (pubspec.yaml) found in inventory."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for missing rust lockfile"
setup
mkdir -p "$TMP/services/rust-worker"
cat > "$TMP/services/rust-worker/Cargo.toml" <<'EOF'
[package]
name = "rust-worker"
version = "0.1.0"
edition = "2021"
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when Cargo.toml has no Cargo.lock" 1 "$LAST_EXIT"
assert_output_contains "reports missing rust lockfile" "Missing Cargo.lock next to Cargo.toml."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh fails for missing ruby and php lockfiles"
setup
mkdir -p "$TMP/services/ruby-app" "$TMP/services/php-app"
cat > "$TMP/services/ruby-app/Gemfile" <<'EOF'
source "https://rubygems.org"
EOF
cat > "$TMP/services/php-app/composer.json" <<'EOF'
{"name":"acme/php-app"}
EOF
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails when Gemfile or composer.json has no lockfile" 1 "$LAST_EXIT"
assert_output_contains "reports missing ruby lockfile" "Missing Gemfile.lock next to Gemfile."
assert_output_contains "reports missing php lockfile" "Missing composer.lock next to composer.json."
teardown

echo ""
echo "▶ cicd_sec_03_dependency_chain.sh runs lock primitives from ecosystems.yml"
setup
printf '[package]\nname = "demo"\nversion = "0.1.0"\n' >"$TMP/Cargo.toml"
printf '%090d\n' 0 >"$TMP/Cargo.lock"
echo 'source "https://rubygems.org"' >"$TMP/Gemfile"
: >"$TMP/Gemfile.lock"
echo '{"name":"acme/demo"}' >"$TMP/composer.json"
printf '%0130d\n' 0 >"$TMP/composer.lock"
run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
assert_exit "fails invalid Rust, Ruby, and PHP lockfiles" 1 "$LAST_EXIT"
assert_output_contains "runs Rust contains primitive" "Cargo.lock appears invalid."
assert_output_contains "runs Ruby nonempty primitive" "Gemfile.lock is empty."
assert_output_contains "runs PHP contains primitive" "composer.lock missing packages section"
teardown

echo ""
echo "▶ SEC-03 fails closed for unknown YAML validators"
setup
touch "$TMP/manifest.test"
cat >"$TMP/ecosystems.yml" <<'EOF'
ecosystems:
  test:
    detect:
      any_files: [manifest.test]
    files:
      - name: manifest.test
        rules:
          - validator: validator_does_not_exist
EOF
export SEC03_TEST_ROOT="$TMP"
export SEC03_TEST_REPO_ROOT="$ROOT_DIR"
cat >"$TMP/run-unknown-validator.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
source "${SEC03_TEST_REPO_ROOT}/scripts/lib/feedback.sh"
source "${SEC03_TEST_REPO_ROOT}/scripts/lib/file_patterns.sh"
source "${SEC03_TEST_REPO_ROOT}/scripts/lib/package_scan.sh"
source "${SEC03_TEST_REPO_ROOT}/scripts/checks/domain/package/validators.sh"
source "${SEC03_TEST_REPO_ROOT}/scripts/checks/domain/package/policy_runner.sh"
ECOSYSTEM_POLICY_CONFIG="${SEC03_TEST_ROOT}/ecosystems.yml"
fb_init "CICD-SEC-03-DEPENDENCY-CHAIN" "Dependency chain check" "https://owasp.org/"
fp_init "$SEC03_TEST_ROOT"
cicd_sec_03_run_ecosystem_policy "$SEC03_TEST_ROOT" "test" "$SEC03_TEST_ROOT/manifest.test"
fb_auto_status false
fb_summary
exit "$(fb_exit_code false false)"
EOF
run_check "$TMP/run-unknown-validator.sh"
unset SEC03_TEST_ROOT SEC03_TEST_REPO_ROOT
assert_exit "unknown validator is an error finding" 1 "$LAST_EXIT"
assert_output_contains "unknown validator names the misconfiguration" "Unknown SEC-03 validator 'validator_does_not_exist'"
teardown

echo ""
echo "▶ cicd_sec_05_runner_access.sh"
setup
cat > "$TMP/.github/workflows/ci.yml" <<'EOF'
name: Test
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo hello
EOF
cat > "$TMP/bin/yq" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == ".jobs | to_entries | .[] | select(.value[\"runs-on\"] == \"self-hosted\") | .key" ]]; then
  echo "test"
  exit 0
fi
exit 0
EOF
chmod +x "$TMP/bin/yq"
PATH="$TMP/bin:$PATH" run_check "$DOMAIN_DIR/cicd_sec_05_runner_access.sh" "$TMP"
assert_exit "warns about generic self-hosted labels" 0 "$LAST_EXIT"
assert_output_contains "uses SEC-05 runner access designation" "CICD-SEC-05-RUNNER-ACCESS"
teardown

echo ""
echo "▶ cicd_sec_07_runner_hardening.sh"
setup
cat > "$TMP/.github/workflows/ci.yml" <<'EOF'
name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      options: --privileged
    steps:
      - run: sudo whoami
EOF
cat > "$TMP/bin/yq" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == ".jobs | to_entries | .[] | select(.value.container.options != null) | select(.value.container.options | test(\"--privileged\")) | .key" ]]; then
  echo "test"
  exit 0
fi
exit 0
EOF
chmod +x "$TMP/bin/yq"
PATH="$TMP/bin:$PATH" run_check "$DOMAIN_DIR/cicd_sec_07_runner_hardening.sh" "$TMP"
assert_exit "fails on privileged runner configuration" 1 "$LAST_EXIT"
assert_output_contains "uses SEC-07 hardening designation" "CICD-SEC-07-RUNNER-HARDENING"
teardown

echo ""
echo "▶ cicd_sec_01_flow.sh"
setup
cat > "$TMP/bin/gh" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == "api" && "$2" == repos/example/repo ]]; then
  echo '{"default_branch":"main"}'
  exit 0
fi
if [[ "$1" == "api" && "$2" == repos/example/repo/branches/main/protection ]]; then
  cat <<JSON
{
  "required_pull_request_reviews": {"required_approving_review_count": 0},
  "allow_force_pushes": {"enabled": true},
  "allow_deletions": {"enabled": false},
  "enforce_admins": {"enabled": true}
}
JSON
  exit 0
fi
exit 1
EOF
cat > "$TMP/bin/jq" <<'EOF'
#!/usr/bin/env bash
python3 -c "import json,sys; d=json.load(sys.stdin); q=sys.argv[1] if len(sys.argv)>1 else '.'
if q=='.': print(json.dumps(d)); sys.exit(0)
if 'default_branch' in q: print(d.get('default_branch','')); sys.exit(0)
if 'required_pull_request_reviews // empty' in q: v=d.get('required_pull_request_reviews'); print('' if v in (None,{}) else json.dumps(v)); sys.exit(0)
if 'required_approving_review_count' in q: print(d.get('required_pull_request_reviews',{}).get('required_approving_review_count',0)); sys.exit(0)
if 'allow_force_pushes.enabled' in q: print(str(d.get('allow_force_pushes',{}).get('enabled',False)).lower()); sys.exit(0)
if 'allow_deletions.enabled' in q: print(str(d.get('allow_deletions',{}).get('enabled',False)).lower()); sys.exit(0)
if 'enforce_admins.enabled' in q: print(str(d.get('enforce_admins',{}).get('enabled',False)).lower()); sys.exit(0)
print('')"
EOF
chmod +x "$TMP/bin/gh" "$TMP/bin/jq"
PATH="$TMP/bin:$PATH" GITHUB_REPOSITORY="example/repo" run_check "$DOMAIN_DIR/cicd_sec_01_flow.sh"
assert_exit "fails on weak flow controls" 1 "$LAST_EXIT"
assert_output_contains "uses SEC-01 flow designation" "CICD-SEC-01-FLOW"
assert_output_contains "includes Scan coverage block" "### Scan coverage"
teardown

echo ""
echo "▶ cicd_sec_05_branch.sh"
setup
cat > "$TMP/bin/gh" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == "api" && "$2" == repos/example/repo ]]; then
  echo '{"default_branch":"main"}'
  exit 0
fi
if [[ "$1" == "api" && "$2" == repos/example/repo/branches/main/protection ]]; then
  cat <<JSON
{
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": false,
    "require_code_owner_reviews": false
  },
  "enforce_admins": {"enabled": false}
}
JSON
  exit 0
fi
exit 1
EOF
cat > "$TMP/bin/jq" <<'EOF'
#!/usr/bin/env bash
python3 -c "import json,sys; d=json.load(sys.stdin); q=sys.argv[1] if len(sys.argv)>1 else '.'
if q=='.': print(json.dumps(d)); sys.exit(0)
if 'default_branch' in q: print(d.get('default_branch','')); sys.exit(0)
if 'dismiss_stale_reviews' in q: print(str(d.get('required_pull_request_reviews',{}).get('dismiss_stale_reviews',False)).lower()); sys.exit(0)
if 'require_code_owner_reviews' in q: print(str(d.get('required_pull_request_reviews',{}).get('require_code_owner_reviews',False)).lower()); sys.exit(0)
if 'enforce_admins.enabled' in q: print(str(d.get('enforce_admins',{}).get('enabled',False)).lower()); sys.exit(0)
print('')"
EOF
chmod +x "$TMP/bin/gh" "$TMP/bin/jq"
PATH="$TMP/bin:$PATH" GITHUB_REPOSITORY="example/repo" run_check "$DOMAIN_DIR/cicd_sec_05_branch.sh"
assert_exit "reports branch policy findings with deterministic designation" 1 "$LAST_EXIT"
assert_output_contains "uses SEC-05 branch designation" "CICD-SEC-05-BRANCH"
teardown

echo ""
echo "▶ cicd_sec_06_secret_scan.sh reports structured gitleaks findings"
setup
git -C "$TMP" init -q
git -C "$TMP" config user.email "guardrails@test.invalid"
git -C "$TMP" config user.name "guardrails-test"
echo "fixture" > "$TMP/readme.md"
git -C "$TMP" add readme.md
git -C "$TMP" commit -q -m "init"
cat > "$TMP/gitleaks" <<'EOF'
#!/usr/bin/env bash
report_path=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --report-path) report_path="$2"; shift 2 ;;
    *) shift ;;
  esac
done
if [[ -n "$report_path" ]]; then
  cat >"$report_path" <<'JSON'
[
  {
    "RuleID": "generic-api-key",
    "File": "config/app.env",
    "StartLine": 3,
    "Commit": "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  },
  {
    "RuleID": "jwt",
    "File": "config/app.env",
    "StartLine": 3,
    "Commit": "cafebabecafebabecafebabecafebabecafebabe"
  },
  {
    "RuleID": "generic-api-key",
    "File": "config/app.env",
    "StartLine": 3,
    "Commit": "feedfeedfeedfeedfeedfeedfeedfeedfeedfeed"
  }
]
JSON
fi
exit 1
EOF
chmod +x "$TMP/gitleaks"
pushd "$TMP" >/dev/null
run_check "$DOMAIN_DIR/cicd_sec_06_secret_scan.sh" .
popd >/dev/null
assert_exit "leaks fail in default fail mode" 1 "$LAST_EXIT"
assert_output_contains "lists file line and rule in Found" "[error] config/app.env:3"
assert_output_contains "lists gitleaks rule id" 'gitleaks rule "generic-api-key"'
assert_output_contains "lists second rule on same line" 'gitleaks rule "jwt"'
assert_output_contains "SEC-06 phase gitleaks" "phase: gitleaks"
if [[ "$(printf '%s' "$LAST_OUTPUT" | grep -c 'config/app.env:3')" -eq 2 ]]; then
  echo "  ✅ dedupes findings per file line and rule"
  PASS=$((PASS + 1))
else
  echo "  ❌ dedupes findings per file line and rule (expected 2 lines, got $(printf '%s' "$LAST_OUTPUT" | grep -c 'config/app.env:3' || true))"
  FAIL=$((FAIL + 1))
fi
teardown

if command -v yq >/dev/null 2>&1; then
  echo ""
  echo "▶ cicd_sec_06_secret_scan.sh with mode=warn"
  setup
  git -C "$TMP" init -q
  git -C "$TMP" config user.email "guardrails@test.invalid"
  git -C "$TMP" config user.name "guardrails-test"
  echo "fixture" > "$TMP/readme.md"
  git -C "$TMP" add readme.md
  git -C "$TMP" commit -q -m "init"
  cat > "$TMP/gitleaks" <<'EOF'
#!/usr/bin/env bash
report_path=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --report-path) report_path="$2"; shift 2 ;;
    *) shift ;;
  esac
done
[[ -n "$report_path" ]] && printf '%s\n' '[{"RuleID":"generic-api-key","File":"secrets.env","StartLine":1,"Commit":"abc12345"}]' >"$report_path"
exit 1
EOF
  chmod +x "$TMP/gitleaks"
  write_guardrails_yml "$TMP" "warn" "CICD-SEC-06-SECRET-SCAN"
  pushd "$TMP" >/dev/null
  run_check "$DOMAIN_DIR/cicd_sec_06_secret_scan.sh" .
  popd >/dev/null
  assert_exit "warn override keeps job green" 0 "$LAST_EXIT"
  assert_output_contains "renders Mode warn" "Mode: **warn**"
  assert_output_contains "renders WARN status" "Status: **WARN**"
  assert_output_contains "still lists finding detail" "secrets.env:1"
  teardown
fi

# ── Per-check severity override (mode warn / off) ─────────────────────────
if command -v yq >/dev/null 2>&1; then
  echo ""
  echo "▶ cicd_sec_03_dependency_chain.sh with mode=warn"
  setup
  echo '{"name":"demo"}' > "$TMP/package.json"
  write_guardrails_yml "$TMP" "warn" "CICD-SEC-03-DEPENDENCY-CHAIN"
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "warn override keeps job green" 0 "$LAST_EXIT"
  assert_output_contains "renders Mode warn" "Mode: **warn**"
  assert_output_contains "renders WARN status" "Status: **WARN**"
  teardown

  echo ""
  echo "▶ cicd_sec_03_dependency_chain.sh with mode=off"
  setup
  cat >"$TMP/go.mod" <<'EOF'
module example.com/mode-off

go 1.22
EOF
  write_guardrails_yml "$TMP" "off" "CICD-SEC-03-DEPENDENCY-CHAIN"
  cat >>"$TMP/.guardrails.yml" <<'EOF'
    ecosystems:
      go: fail
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "off override keeps job green" 0 "$LAST_EXIT"
  assert_output_contains "renders Mode off" "Mode: **off**"
  assert_output_contains "renders SKIPPED status" "Status: **SKIPPED**"
  assert_output_not_contains "mode off suppresses Go findings before inventory" "Missing go.sum"
  teardown
else
  echo ""
  echo "▶ skipping mode override tests (yq not available)"
fi

# ── SEC-03 per-ecosystem gates ────────────────────────────────────────────
if command -v yq >/dev/null 2>&1; then
  echo ""
  echo "▶ SEC-03 disables Go while keeping the check active"
  setup
  cat >"$TMP/go.mod" <<'EOF'
module example.com/go-off

go 1.22
EOF
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      go: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "Go off keeps a broken Go-only repo green" 0 "$LAST_EXIT"
  assert_output_not_contains "Go off suppresses the missing go.sum finding" "Missing go.sum"
  assert_output_contains "Go off is visible in coverage" "Go skipped by config"
  assert_output_not_contains "ecosystem off does not skip the whole check" "Status: **SKIPPED**"
  teardown

  echo ""
  echo "▶ SEC-03 disables Dart while keeping the check active"
  setup
  printf 'name: dart_off\n' >"$TMP/pubspec.yaml"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      dart: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "Dart off keeps a broken Dart-only repo green" 0 "$LAST_EXIT"
  assert_output_not_contains "Dart off suppresses the missing pubspec.lock finding" "Missing pubspec.lock"
  assert_output_contains "Dart off is visible in coverage" "Dart skipped by config"
  assert_output_not_contains "Dart off does not skip the whole check" "Status: **SKIPPED**"
  teardown

  echo ""
  echo "▶ SEC-03 keeps Python active when Go is off"
  setup
  printf 'module example.com/go-off\n\ngo 1.22\n' >"$TMP/go.mod"
  printf 'requests\n' >"$TMP/requirements.txt"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      go: off
      python: fail
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "active Python still fails when Go is off" 1 "$LAST_EXIT"
  assert_output_contains "Python finding remains active" "Unpinned python dependency 'requests'."
  assert_output_not_contains "Go finding remains suppressed" "Missing go.sum"
  assert_output_contains "mixed repo records Go config skip" "Go skipped by config"
  teardown

  echo ""
  echo "▶ SEC-03 disables JavaScript by config"
  setup
  echo '{"name":"no-lock"}' >"$TMP/package.json"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      javascript: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "JavaScript off suppresses a missing lockfile" 0 "$LAST_EXIT"
  assert_output_not_contains "JavaScript finding is absent" "JavaScript project is missing a lockfile"
  assert_output_contains "JavaScript config skip uses public ecosystem name" "JavaScript skipped by config"
  assert_output_not_contains "coverage does not expose internal js_ts name" "js_ts skipped by config"
  teardown

  echo ""
  echo "▶ SEC-03 defaults missing ecosystem settings to fail"
  setup
  printf 'module example.com/default-go\n\ngo 1.22\n' >"$TMP/go.mod"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    mode: fail
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "missing ecosystems map preserves Go failure" 1 "$LAST_EXIT"
  assert_output_contains "default Go audit reports missing go.sum" "Missing go.sum next to go.mod."
  teardown

  echo ""
  echo "▶ SEC-03 ignores unknown ecosystem keys with notice"
  setup
  echo '{"name":"green"}' >"$TMP/package.json"
  write_empty_npm_lock "$TMP/package-lock.json"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      js_ts: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "unknown ecosystem key does not fail a green repo" 0 "$LAST_EXIT"
  assert_output_contains "unknown ecosystem key emits notice" "Unknown SEC-03 ecosystem key 'js_ts'; ignoring it."
  assert_output_not_contains "unknown key does not disable JavaScript" "JavaScript skipped by config"
  teardown

  echo ""
  echo "▶ SEC-03 allowlist ignores IDs from test-local ecosystem YAML"
  setup
  cat >"$TMP/ecosystems.yml" <<'EOF'
ecosystems:
  test_local:
    label: Test Local
    detect:
      any_files: [manifest.test]
EOF
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      test_local: off
EOF
  cat >"$TMP/check-shipped-allowlist.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
source "${SCRIPTS_DIR}/lib/config.sh"
cfg_init "\$1"
ECOSYSTEM_POLICY_CONFIG="\$2"
cfg_sec03_unknown_ecosystem_keys
EOF
  run_check "$TMP/check-shipped-allowlist.sh" "$TMP" "$TMP/ecosystems.yml"
  assert_exit "test-local ecosystem allowlist probe succeeds" 0 "$LAST_EXIT"
  assert_output_contains "test-local ecosystem remains unknown" "test_local"
  teardown

  echo ""
  echo "▶ SEC-03 defaults invalid known ecosystem values to fail"
  setup
  printf 'module example.com/invalid-go\n\ngo 1.22\n' >"$TMP/go.mod"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      go: warn
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "invalid Go mode still runs failing audit" 1 "$LAST_EXIT"
  assert_output_contains "invalid Go mode emits notice" "Invalid SEC-03 ecosystem mode 'warn' for 'go'; using default 'fail'."
  assert_output_contains "invalid Go mode preserves finding" "Missing go.sum next to go.mod."
  teardown

  echo ""
  echo "▶ SEC-03 disables unsupported ecosystem notices"
  setup
  echo '<project />' >"$TMP/pom.xml"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    unsupported_ecosystems: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "unsupported ecosystems off keeps Maven-only repo green" 0 "$LAST_EXIT"
  assert_output_not_contains "unsupported ecosystems off suppresses Maven notice" "Unsupported Maven"
  assert_output_contains "unsupported config skip is visible" "Unsupported ecosystems skipped by config"
  teardown

  echo ""
  echo "▶ SEC-03 disables Rust Ruby and PHP independently"
  setup
  printf '[package]\nname = "demo"\nversion = "0.1.0"\n' >"$TMP/Cargo.toml"
  echo 'source "https://rubygems.org"' >"$TMP/Gemfile"
  echo '{"name":"acme/demo"}' >"$TMP/composer.json"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      rust: off
      ruby: off
      php: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "three disabled lockfile audits keep repo green" 0 "$LAST_EXIT"
  assert_output_not_contains "Rust lockfile finding is absent" "Missing Cargo.lock"
  assert_output_not_contains "Ruby lockfile finding is absent" "Missing Gemfile.lock"
  assert_output_not_contains "PHP lockfile finding is absent" "Missing composer.lock"
  assert_output_contains "Rust skip is visible" "Rust skipped by config"
  assert_output_contains "Ruby skip is visible" "Ruby skipped by config"
  assert_output_contains "PHP skip is visible" "PHP skipped by config"
  teardown

  echo ""
  echo "▶ SEC-03 Go gate does not affect workflow pinning"
  setup
  printf 'module example.com/go-off\n\ngo 1.22\n' >"$TMP/go.mod"
  cp "$FIXTURES_DIR/bad-pinning.yml" "$TMP/.github/workflows/ci.yml"
  cat >"$TMP/.guardrails.yml" <<'EOF'
checks:
  CICD-SEC-03-DEPENDENCY-CHAIN:
    ecosystems:
      go: off
EOF
  run_check "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh" "$TMP"
  assert_exit "unpinned workflow still fails when Go is off" 1 "$LAST_EXIT"
  assert_output_contains "Go skip remains visible beside workflow finding" "Go skipped by config"
  assert_output_contains "workflow action finding remains active" "actions/checkout@v4"
  teardown
else
  echo ""
  echo "▶ skipping SEC-03 ecosystem gate tests (yq not available)"
fi

echo ""
echo "▶ aggregate_risk_summary.sh"
setup
mkdir -p "$TMP/scan_repo" "$TMP/results"
cat > "$TMP/results/CICD-SEC-01-FLOW.json" <<'EOF'
{"check_id":"CICD-SEC-01-FLOW","title":"Flow control policy check","status":"FAIL","mode":"fail","counts":{"errors":1,"warnings":0,"notices":0},"owasp_reference":"https://owasp.org/www-project-top-10-ci-cd-security-risks/CICD-SEC-01-Insufficient-Flow-Control-Mechanisms/","duration_seconds":3}
EOF
cat > "$TMP/results/CICD-SEC-07-RUNNER-HARDENING.json" <<'EOF'
{"check_id":"CICD-SEC-07-RUNNER-HARDENING","title":"Runner hardening check","status":"FAIL","mode":"fail","counts":{"errors":1,"warnings":0,"notices":0},"owasp_reference":"https://owasp.org/www-project-top-10-ci-cd-security-risks/CICD-SEC-07-Insecure-System-Configuration/"}
EOF
run_check "$SCRIPTS_DIR/aggregate_risk_summary.sh" "$TMP/scan_repo" "$TMP/results"
assert_exit "returns exit 0 for summary output" 0 "$LAST_EXIT"
assert_output_contains "prints executive snapshot" "Executive snapshot:"
assert_output_contains "includes merged per-check scan coverage heading" "### Per-check scan coverage"
assert_output_contains "groups Critical by Code and Settings" "##### Code"
assert_output_contains "groups Critical by Code and Settings (settings bucket)" "##### Settings"
assert_aggregate_critical_scope_order "Critical: Code bucket lists runner hardening before Settings lists flow check"
assert_output_contains "includes OWASP short reference labels" "[OWASP CICD-SEC-01-FLOW]"
assert_output_contains "lists container_registry context" "container_registry:"
assert_output_contains "shows duration next to status in coverage" "duration: \`3s\`"
teardown

if command -v yq >/dev/null 2>&1; then
  echo ""
  echo "▶ aggregate_risk_summary.sh with container_registry=public"
  setup
  mkdir -p "$TMP/scan_repo" "$TMP/results"
  cat > "$TMP/scan_repo/.guardrails.yml" <<'EOF'
context:
  visibility: public
  software_type: open_source
  runner_type: github_hosted
  container_registry: public
  data_sensitivity: medium
  deployment_criticality: dev
EOF
  cat > "$TMP/results/CICD-SEC-08-ACTION-PINNING.json" <<'EOF'
{"check_id":"CICD-SEC-08-ACTION-PINNING","title":"Action pinning check","status":"FAIL","mode":"fail","counts":{"errors":1,"warnings":0,"notices":0},"owasp_reference":"https://owasp.org/www-project-top-10-ci-cd-security-risks/CICD-SEC-08-Ungoverned-Usage-of-3rd-Party-Services/"}
EOF
  run_check "$SCRIPTS_DIR/aggregate_risk_summary.sh" "$TMP/scan_repo" "$TMP/results"
  assert_exit "summary completes with public registry" 0 "$LAST_EXIT"
  assert_output_contains "shows public container_registry" "container_registry: \`public\`"
  teardown

  echo ""
  echo "▶ aggregate_risk_summary.sh shows softened-mode note"
  setup
  mkdir -p "$TMP/scan_repo" "$TMP/results"
  cat > "$TMP/results/CICD-SEC-08-ACTION-PINNING.json" <<'EOF'
{"check_id":"CICD-SEC-08-ACTION-PINNING","title":"Action pinning check","status":"WARN","mode":"warn","counts":{"errors":0,"warnings":1,"notices":0},"owasp_reference":"https://owasp.org/www-project-top-10-ci-cd-security-risks/CICD-SEC-08-Ungoverned-Usage-of-3rd-Party-Services/"}
EOF
  run_check "$SCRIPTS_DIR/aggregate_risk_summary.sh" "$TMP/scan_repo" "$TMP/results"
  assert_exit "summary completes with softened check" 0 "$LAST_EXIT"
  assert_output_contains "shows mode override note" "per-check override"
  teardown

  echo ""
  echo "▶ .guardrails.file-patterns.reference.yml mirrors package_policy.defaults.yml"
  DEFAULTS_YML="${ROOT_DIR}/scripts/config/package_policy.defaults.yml"
  REF_YML="${ROOT_DIR}/.guardrails.file-patterns.reference.yml"
  runtime_excludes() {
    bash -c "source '${ROOT_DIR}/scripts/lib/file_patterns.sh'; fp_default_excludes"
  }
  # JSON detour drops the per-entry documentation comments in the reference file.
  reference_excludes() {
    yq -oj '.global_excludes' "$REF_YML" \
      | python3 -c 'import json, sys
for item in json.load(sys.stdin):
    print(item)'
  }
  if diff -q <(runtime_excludes) <(reference_excludes) >/dev/null 2>&1; then
    echo "  ✅ reference global_excludes matches fp_default_excludes"
    PASS=$((PASS + 1))
  else
    echo "  ❌ reference global_excludes drifts from scripts/lib/file_patterns.sh"
    diff -u <(runtime_excludes) <(reference_excludes) || true
    FAIL=$((FAIL + 1))
  fi
  # JSON-normalized compare ignores header comments in the flat defaults file.
  if diff -q <(yq eval -oj '.' "$DEFAULTS_YML") <(yq eval -oj '.package_policy.python' "$REF_YML") >/dev/null 2>&1; then
    echo "  ✅ reference package_policy.python matches shipped defaults"
    PASS=$((PASS + 1))
  else
    echo "  ❌ reference package_policy.python drifts from scripts/config/package_policy.defaults.yml"
    diff -u <(yq eval -oj '.' "$DEFAULTS_YML") <(yq eval -oj '.package_policy.python' "$REF_YML") || true
    FAIL=$((FAIL + 1))
  fi
  JS_DEFAULTS_YML="${ROOT_DIR}/scripts/config/package_policy.javascript.defaults.yml"
  if diff -q <(yq eval -oj '.' "$JS_DEFAULTS_YML") <(yq eval -oj '.package_policy.javascript' "$REF_YML") >/dev/null 2>&1; then
    echo "  ✅ reference package_policy.javascript matches shipped defaults"
    PASS=$((PASS + 1))
  else
    echo "  ❌ reference package_policy.javascript drifts from shipped defaults"
    diff -u <(yq eval -oj '.' "$JS_DEFAULTS_YML") <(yq eval -oj '.package_policy.javascript' "$REF_YML") || true
    FAIL=$((FAIL + 1))
  fi
  ECOSYSTEMS_YML="${ROOT_DIR}/scripts/config/ecosystems.yml"
  EXPECTED_GO_ECOSYSTEM="$(mktemp)"
  cat >"$EXPECTED_GO_ECOSYSTEM" <<'EOF'
label: Go
detect:
  any_files: [go.mod]
files:
  - name: go.mod
    rules:
      - require_sibling: [go.sum]
        message: "Missing go.sum next to go.mod."
        remediation: "Run go mod tidy and commit go.sum."
  - name: go.sum
    rules:
      - not_empty: true
        message: "go.sum is empty."
        remediation: "Run go mod tidy and commit go.sum."
EOF
  if diff -q <(yq eval -oj '.ecosystems.go' "$ECOSYSTEMS_YML") <(yq eval -oj '.' "$EXPECTED_GO_ECOSYSTEM") >/dev/null 2>&1; then
    echo "  ✅ ecosystems.yml Go policy matches the Epic schema"
    PASS=$((PASS + 1))
  else
    echo "  ❌ ecosystems.yml Go policy drifts from the Epic schema"
    diff -u <(yq eval -oj '.ecosystems.go' "$ECOSYSTEMS_YML") <(yq eval -oj '.' "$EXPECTED_GO_ECOSYSTEM") || true
    FAIL=$((FAIL + 1))
  fi
  if [[ "$(yq -r '.ecosystems.javascript.files[] | select(.name == "package.json") | .rules[].validator' "$ECOSYSTEMS_YML")" == "javascript_package_policy" ]]; then
    echo "  ✅ ecosystems.yml dispatches JavaScript through a named validator"
    PASS=$((PASS + 1))
  else
    echo "  ❌ ecosystems.yml does not dispatch JavaScript through its named validator"
    FAIL=$((FAIL + 1))
  fi
  if ! grep -Eq 'source .*(js_ts|python|rust|ruby|php)\.sh' "$DOMAIN_DIR/cicd_sec_03_dependency_chain.sh"; then
    echo "  ✅ SEC-03 no longer sources legacy ecosystem audit scripts"
    PASS=$((PASS + 1))
  else
    echo "  ❌ SEC-03 still sources a legacy ecosystem audit script"
    FAIL=$((FAIL + 1))
  fi
  rm -f "$EXPECTED_GO_ECOSYSTEM"
fi

echo ""
echo "═══════════════════════════════════════"
echo "  $PASS passed  |  $FAIL failed"
echo "═══════════════════════════════════════"

[[ $FAIL -eq 0 ]] || exit 1
