#!/usr/bin/env bash

set -euo pipefail

sec03__validate_package_json_specs() {
  local path_root="$1"
  local manifest="$2"
  local rel
  rel="$(pkg_rel_path "$path_root" "$manifest")"
  while IFS='|' read -r kind line name spec; do
    [[ -z "$kind" ]] && continue
    case "$kind" in
      INVALID_JSON)
        fb_report "error" "package.json is not valid JSON." "$rel" "" \
          "Fix package.json syntax and commit a lockfile generated by the selected package manager." "js_ts"
        ;;
      INVALID_SPEC)
        fb_report "error" "JavaScript dependency '${name}' is not pinned to an allowed immutable spec ('${spec}')." "$rel" "$line" \
          "Use an exact SemVer (optionally '='), file:/link:/workspace:, an exact npm: alias, or a Git/URL reference with a full commit SHA." "js_ts"
        ;;
    esac
  done < <(
    python3 - "$manifest" <<'PY'
import json
import re
import sys

path = sys.argv[1]
try:
    text = open(path, encoding="utf-8", errors="replace").read()
    data = json.loads(text)
except (OSError, json.JSONDecodeError):
    print("INVALID_JSON|||")
    raise SystemExit

exact = re.compile(
    r"^=?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
full_sha = re.compile(r"^[0-9a-fA-F]{40}$")


def immutable(spec):
    if exact.fullmatch(spec):
        return True
    if spec.startswith(("file:", "link:", "workspace:")):
        return len(spec.split(":", 1)[1]) > 0
    if spec.startswith("npm:"):
        target = spec[4:]
        at = target.rfind("@")
        return at > 0 and exact.fullmatch(target[at + 1 :]) is not None
    looks_remote = (
        "://" in spec
        or spec.startswith(("git+", "git@", "github:", "gitlab:", "bitbucket:"))
        or re.match(r"^[^/\s]+/[^#\s]+#", spec)
    )
    if looks_remote and "#" in spec:
        return full_sha.fullmatch(spec.rsplit("#", 1)[1]) is not None
    return False


lines = text.splitlines()
for section in ("dependencies", "devDependencies", "optionalDependencies"):
    deps = data.get(section, {})
    if deps is None:
        continue
    if not isinstance(deps, dict):
        print(f"INVALID_SPEC||{section}|non-object")
        continue
    for name, spec in deps.items():
        value = spec if isinstance(spec, str) else json.dumps(spec, separators=(",", ":"))
        if isinstance(spec, str) and immutable(spec):
            continue
        line = next(
            (i for i, row in enumerate(lines, 1) if re.search(rf'"{re.escape(name)}"\s*:', row)),
            "",
        )
        print(f"INVALID_SPEC|{line}|{name}|{value}")
PY
  )
}

sec03__validate_npm_lock_integrity() {
  local path_root="$1"
  local lockfile="$2"
  local rel result
  rel="$(pkg_rel_path "$path_root" "$lockfile")"
  result="$(
    python3 - "$lockfile" <<'PY'
import json
import sys

try:
    data = json.load(open(sys.argv[1], encoding="utf-8"))
except (OSError, json.JSONDecodeError):
    print("invalid_json")
    raise SystemExit
if data.get("lockfileVersion") not in (2, 3):
    print("unsupported_version")
    raise SystemExit
packages = data.get("packages")
if not isinstance(packages, dict):
    print("missing_packages")
    raise SystemExit
for key, package in packages.items():
    if not key or not isinstance(package, dict):
        continue
    if package.get("link") or "resolved" not in package:
        continue
    resolved = str(package.get("resolved", ""))
    if resolved.startswith(("file:", "link:")):
        continue
    integrity = package.get("integrity")
    if not isinstance(integrity, str) or not integrity.startswith(("sha512-", "sha384-", "sha256-", "sha1-")):
        print(f"missing_integrity:{key}")
        raise SystemExit
PY
  )"
  [[ -z "$result" ]] && return 0
  fb_report "error" "package-lock.json lacks valid integrity evidence (${result})." "$rel" "" \
    "Regenerate package-lock.json with a current npm version and commit the complete lockfile." "js_ts"
}

sec03__validate_yarn_lock_integrity() {
  local path_root="$1"
  local lockfile="$2"
  local rel result
  rel="$(pkg_rel_path "$path_root" "$lockfile")"
  result="$(
    python3 - "$lockfile" <<'PY'
import re
import sys

text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
if not text.strip():
    print("empty")
    raise SystemExit
if "__metadata:" in text:
    if not re.search(r"(?m)^\s+version:\s*[2-9][0-9]*\s*$", text):
        print("invalid_berry_metadata")
        raise SystemExit
    blocks = re.split(r'(?m)^(?="[^"]+":\s*$)', text)
    for block in blocks:
        if not re.match(r'^"[^"]+":\s*$', block.splitlines()[0] if block.splitlines() else ""):
            continue
        resolution = re.search(r'(?m)^\s+resolution:\s+"?([^"\n]+)"?', block)
        if resolution and "@workspace:" not in resolution.group(1) and not re.search(r"(?m)^\s+checksum:\s+\S+", block):
            print("berry_entry_without_checksum")
            raise SystemExit
else:
    if "yarn lockfile v1" not in text[:256]:
        print("unknown_format")
        raise SystemExit
    blocks = re.split(r"(?m)^(?=\S.*:\s*$)", text)
    for block in blocks:
        if re.search(r'(?m)^\s+resolved\s+"?https?://', block) and not re.search(
            r"(?m)^\s+integrity\s+sha(?:1|256|384|512)-\S+", block
        ):
            print("classic_entry_without_integrity")
            raise SystemExit
PY
  )"
  [[ -z "$result" ]] && return 0
  fb_report "error" "yarn.lock lacks valid Yarn Classic integrity or Yarn Berry checksum evidence (${result})." "$rel" "" \
    "Regenerate yarn.lock with the project's Yarn version and commit all integrity/checksum fields." "js_ts"
}

sec03__validate_pnpm_lock_integrity() {
  local path_root="$1"
  local lockfile="$2"
  local rel result
  rel="$(pkg_rel_path "$path_root" "$lockfile")"
  result="$(
    python3 - "$lockfile" <<'PY'
import re
import sys

lines = open(sys.argv[1], encoding="utf-8", errors="replace").read().splitlines()
if not any(re.match(r"^lockfileVersion:\s*\S+", line) for line in lines):
    print("missing_lockfile_version")
    raise SystemExit
try:
    start = next(i for i, line in enumerate(lines) if line.strip() == "packages:")
except StopIteration:
    raise SystemExit
entries = []
for i in range(start + 1, len(lines)):
    line = lines[i]
    if line and not line.startswith(" ") and line.endswith(":"):
        break
    match = re.match(r"^  (\S.*):\s*$", line)
    if match:
        entries.append((match.group(1).strip("'\""), i))
for index, (name, begin) in enumerate(entries):
    if name.startswith(("file:", "link:", "workspace:")):
        continue
    end = entries[index + 1][1] if index + 1 < len(entries) else len(lines)
    block = "\n".join(lines[begin:end])
    if not re.search(r"integrity:\s*sha(?:1|256|384|512)-\S+", block):
        print("package_entry_without_integrity")
        raise SystemExit
PY
  )"
  [[ -z "$result" ]] && return 0
  fb_report "error" "pnpm-lock.yaml lacks valid package integrity evidence (${result})." "$rel" "" \
    "Regenerate pnpm-lock.yaml with a current pnpm version and commit the complete lockfile." "js_ts"
}

sec03__run_js_hash_validator() {
  local validator="$1"
  local path_root="$2"
  local lockfile="$3"
  case "$validator" in
    npm_lock_integrity) sec03__validate_npm_lock_integrity "$path_root" "$lockfile" ;;
    yarn_lock_integrity) sec03__validate_yarn_lock_integrity "$path_root" "$lockfile" ;;
    pnpm_lock_integrity) sec03__validate_pnpm_lock_integrity "$path_root" "$lockfile" ;;
    *)
      fb_report "warning" "Unknown JavaScript lock validator '${validator}'." "$(pkg_rel_path "$path_root" "$lockfile")" "" \
        "Fix package_policy.javascript.hash_validators in the defaults or overlay." "js_ts"
      ;;
  esac
}

sec03__javascript_trigger_combo_allowed() {
  local path_root="$1"
  local dir="$2"
  shift 2
  local -a triggers=("$@")
  local trigger_key combo
  trigger_key="$(printf '%s\n' "${triggers[@]}" | sort -u | paste -sd' ' -)"
  while IFS= read -r combo; do
    [[ -z "$combo" ]] && continue
    [[ "$trigger_key" == "$combo" ]] && return 0
  done < <(pp_javascript_allowed_combo_sorted_space_lines)

  local rel_probe
  rel_probe="$(pkg_rel_path "$path_root" "${dir}/${triggers[0]}")"
  fb_report "error" "Ambiguous JavaScript/TypeScript project triggers in one directory: ${triggers[*]}." "$rel_probe" "" \
    "Keep one allowed trigger combination: package.json alone, tsconfig.json with package.json, or jsconfig.json with package.json." "js_ts"
  return 1
}

cicd_sec_03_run_javascript_package_policy() {
  local path_root="$1"
  local -a project_dirs=()
  while IFS= read -r dir; do
    [[ -n "$dir" ]] && project_dirs+=("$dir")
  done < <(
    local trigger artifact rel
    while IFS= read -r trigger; do
      [[ -z "$trigger" ]] && continue
      while IFS= read -r artifact; do
        [[ -z "$artifact" || ! -f "$artifact" ]] && continue
        rel="$(pkg_rel_path "$path_root" "$artifact")"
        fp_should_skip_validation "$rel" && continue
        dirname "$artifact"
      done < <(fp_find_with_names "$path_root" "$trigger")
    done < <(pp_javascript_trigger_names) | sort -u
  )

  local dir
  for dir in "${project_dirs[@]+"${project_dirs[@]}"}"; do
    local -a triggers=()
    local trigger
    while IFS= read -r trigger; do
      [[ -n "$trigger" && -f "${dir}/${trigger}" ]] && triggers+=("$trigger")
    done < <(pp_javascript_trigger_names | sort -u)
    ((${#triggers[@]} == 0)) && continue

    if [[ ! -f "${dir}/package.json" ]]; then
      local rel_trigger
      rel_trigger="$(pkg_rel_path "$path_root" "${dir}/${triggers[0]}")"
      fb_report "error" "JavaScript/TypeScript project is missing package.json beside ${triggers[0]}." "$rel_trigger" "" \
        "Add package.json beside the project config, then generate and commit exactly one supported lockfile in the same directory." "js_ts"
      continue
    fi

    sec03__javascript_trigger_combo_allowed "$path_root" "$dir" "${triggers[@]}" || true
    cicd_sec_03_audit_js_ts_package_json "$path_root" "${dir}/package.json" || true
  done
}

cicd_sec_03_audit_js_ts_package_json() {
  local path_root="$1"
  local manifest="$2"
  local rel
  rel="$(pkg_rel_path "$path_root" "$manifest")"
  if fp_should_skip_validation "$rel"; then
    return 0
  fi
  sec03__validate_package_json_specs "$path_root" "$manifest"

  local dir
  dir="$(dirname "$manifest")"
  local -a present=()
  local satisfier
  while IFS= read -r satisfier; do
    [[ -n "$satisfier" && -f "${dir}/${satisfier}" ]] && present+=("$satisfier")
  done < <(pp_javascript_satisfier_names)

  if ((${#present[@]} == 0)); then
    fb_report "error" "JavaScript project is missing a lockfile in the package.json directory." "$rel" "" \
      "Generate and commit exactly one of package-lock.json, yarn.lock, or pnpm-lock.yaml beside package.json." "js_ts"
    return 0
  fi
  if ((${#present[@]} > 1)); then
    fb_report "error" "JavaScript project has multiple lockfile families in one directory: ${present[*]}." "$rel" "" \
      "Keep exactly one package-manager lockfile family beside package.json." "js_ts"
    return 0
  fi

  local validator
  validator="$(pp_javascript_validator_for "${present[0]}")"
  sec03__run_js_hash_validator "$validator" "$path_root" "${dir}/${present[0]}"
}

cicd_sec_03_audit_js_ts_lock_package_lock() {
  :
}

cicd_sec_03_audit_js_ts_lock_yarn() {
  :
}

cicd_sec_03_audit_js_ts_lock_pnpm() {
  :
}
