#!/usr/bin/env bash

# Named SEC-03 validators and package-policy runners.
# Sourced by cicd_sec_03_dependency_chain.sh; callers provide fb_*, fp_*, pkg_*,
# pp_* and cicd_sec_03_run_named_validator.

set -euo pipefail

sec03_validate_package_json_exact_specs() {
  local path_root="$1" manifest="$2" rel
  rel="$(pkg_rel_path "$path_root" "$manifest")"
  while IFS='|' read -r kind line name spec; do
    [[ -z "$kind" ]] && continue
    case "$kind" in
      INVALID_JSON)
        fb_report "error" "package.json is not valid JSON." "$rel" "" \
          "Fix package.json syntax and commit a lockfile generated by the selected package manager." "js_ts"
        ;;
      INVALID_SPEC)
        fb_report "error" "JavaScript dependency '${name}' is not pinned to an allowed immutable spec ('${spec}')." "$rel" "$line" \
          "Use an exact SemVer (optionally '='), file:/link:/workspace:, an exact npm: alias, or a Git/URL reference with a full commit SHA." "js_ts"
        ;;
    esac
  done < <(
    python3 - "$manifest" <<'PY'
import json
import re
import sys

path = sys.argv[1]
try:
    text = open(path, encoding="utf-8", errors="replace").read()
    data = json.loads(text)
except (OSError, json.JSONDecodeError):
    print("INVALID_JSON|||")
    raise SystemExit

exact = re.compile(
    r"^=?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
full_sha = re.compile(r"^[0-9a-fA-F]{40}$")


def immutable(spec):
    if exact.fullmatch(spec):
        return True
    if spec.startswith(("file:", "link:", "workspace:")):
        return len(spec.split(":", 1)[1]) > 0
    if spec.startswith("npm:"):
        target = spec[4:]
        at = target.rfind("@")
        return at > 0 and exact.fullmatch(target[at + 1 :]) is not None
    looks_remote = (
        "://" in spec
        or spec.startswith(("git+", "git@", "github:", "gitlab:", "bitbucket:"))
        or re.match(r"^[^/\s]+/[^#\s]+#", spec)
    )
    if looks_remote and "#" in spec:
        return full_sha.fullmatch(spec.rsplit("#", 1)[1]) is not None
    return False


lines = text.splitlines()
for section in ("dependencies", "devDependencies", "optionalDependencies"):
    deps = data.get(section, {})
    if deps is None:
        continue
    if not isinstance(deps, dict):
        print(f"INVALID_SPEC||{section}|non-object")
        continue
    for name, spec in deps.items():
        value = spec if isinstance(spec, str) else json.dumps(spec, separators=(",", ":"))
        if isinstance(spec, str) and immutable(spec):
            continue
        line = next(
            (i for i, row in enumerate(lines, 1) if re.search(rf'"{re.escape(name)}"\s*:', row)),
            "",
        )
        print(f"INVALID_SPEC|{line}|{name}|{value}")
PY
  )
}

sec03_validate_npm_lock_integrity() {
  local path_root="$1" lockfile="$2" rel result
  rel="$(pkg_rel_path "$path_root" "$lockfile")"
  result="$(
    python3 - "$lockfile" <<'PY'
import json
import sys

try:
    data = json.load(open(sys.argv[1], encoding="utf-8"))
except (OSError, json.JSONDecodeError):
    print("invalid_json")
    raise SystemExit
if data.get("lockfileVersion") not in (2, 3):
    print("unsupported_version")
    raise SystemExit
packages = data.get("packages")
if not isinstance(packages, dict):
    print("missing_packages")
    raise SystemExit
for key, package in packages.items():
    if not key or not isinstance(package, dict):
        continue
    if package.get("link") or "resolved" not in package:
        continue
    resolved = str(package.get("resolved", ""))
    if resolved.startswith(("file:", "link:")):
        continue
    integrity = package.get("integrity")
    if not isinstance(integrity, str) or not integrity.startswith(("sha512-", "sha384-", "sha256-", "sha1-")):
        print(f"missing_integrity:{key}")
        raise SystemExit
PY
  )"
  [[ -z "$result" ]] && return 0
  fb_report "error" "package-lock.json lacks valid integrity evidence (${result})." "$rel" "" \
    "Regenerate package-lock.json with a current npm version and commit the complete lockfile." "js_ts"
}

sec03_validate_yarn_lock_integrity() {
  local path_root="$1" lockfile="$2" rel result
  rel="$(pkg_rel_path "$path_root" "$lockfile")"
  result="$(
    python3 - "$lockfile" <<'PY'
import re
import sys

text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
if not text.strip():
    print("empty")
    raise SystemExit
if "__metadata:" in text:
    if not re.search(r"(?m)^\s+version:\s*[2-9][0-9]*\s*$", text):
        print("invalid_berry_metadata")
        raise SystemExit
    blocks = re.split(r'(?m)^(?="[^"]+":\s*$)', text)
    for block in blocks:
        if not re.match(r'^"[^"]+":\s*$', block.splitlines()[0] if block.splitlines() else ""):
            continue
        resolution = re.search(r'(?m)^\s+resolution:\s+"?([^"\n]+)"?', block)
        if resolution and "@workspace:" not in resolution.group(1) and not re.search(r"(?m)^\s+checksum:\s+\S+", block):
            print("berry_entry_without_checksum")
            raise SystemExit
else:
    if "yarn lockfile v1" not in text[:256]:
        print("unknown_format")
        raise SystemExit
    blocks = re.split(r"(?m)^(?=\S.*:\s*$)", text)
    for block in blocks:
        if re.search(r'(?m)^\s+resolved\s+"?https?://', block) and not re.search(
            r"(?m)^\s+integrity\s+sha(?:1|256|384|512)-\S+", block
        ):
            print("classic_entry_without_integrity")
            raise SystemExit
PY
  )"
  [[ -z "$result" ]] && return 0
  fb_report "error" "yarn.lock lacks valid Yarn Classic integrity or Yarn Berry checksum evidence (${result})." "$rel" "" \
    "Regenerate yarn.lock with the project's Yarn version and commit all integrity/checksum fields." "js_ts"
}

sec03_validate_pnpm_lock_integrity() {
  local path_root="$1" lockfile="$2" rel result
  rel="$(pkg_rel_path "$path_root" "$lockfile")"
  result="$(
    python3 - "$lockfile" <<'PY'
import re
import sys

lines = open(sys.argv[1], encoding="utf-8", errors="replace").read().splitlines()
if not any(re.match(r"^lockfileVersion:\s*\S+", line) for line in lines):
    print("missing_lockfile_version")
    raise SystemExit
try:
    start = next(i for i, line in enumerate(lines) if line.strip() == "packages:")
except StopIteration:
    raise SystemExit
entries = []
for i in range(start + 1, len(lines)):
    line = lines[i]
    if line and not line.startswith(" ") and line.endswith(":"):
        break
    match = re.match(r"^  (\S.*):\s*$", line)
    if match:
        entries.append((match.group(1).strip("'\""), i))
for index, (name, begin) in enumerate(entries):
    if name.startswith(("file:", "link:", "workspace:")):
        continue
    end = entries[index + 1][1] if index + 1 < len(entries) else len(lines)
    block = "\n".join(lines[begin:end])
    if not re.search(r"integrity:\s*sha(?:1|256|384|512)-\S+", block):
        print("package_entry_without_integrity")
        raise SystemExit
PY
  )"
  [[ -z "$result" ]] && return 0
  fb_report "error" "pnpm-lock.yaml lacks valid package integrity evidence (${result})." "$rel" "" \
    "Regenerate pnpm-lock.yaml with a current pnpm version and commit the complete lockfile." "js_ts"
}

sec03_javascript_trigger_combo_allowed() {
  local path_root="$1" dir="$2"
  shift 2
  local -a triggers=("$@")
  local trigger_key combo allowed=false
  trigger_key="$(printf '%s\n' "${triggers[@]}" | sort -u | paste -sd' ' -)"
  while IFS= read -r combo; do
    [[ -z "$combo" ]] && continue
    [[ "$trigger_key" == "$combo" ]] && allowed=true
  done < <(pp_javascript_allowed_combo_sorted_space_lines)
  $allowed && return 0

  local rel_probe
  rel_probe="$(pkg_rel_path "$path_root" "${dir}/${triggers[0]}")"
  fb_report "error" "Ambiguous JavaScript/TypeScript project triggers in one directory: ${triggers[*]}." "$rel_probe" "" \
    "Keep one allowed trigger combination: package.json alone, tsconfig.json with package.json, or jsconfig.json with package.json." "js_ts"
  return 1
}

sec03_validate_javascript_package_policy() {
  local path_root="$1" detector="$2"
  local dir
  dir="$(dirname "$detector")"
  local -a triggers=()
  local trigger
  while IFS= read -r trigger; do
    [[ -n "$trigger" && -f "${dir}/${trigger}" ]] && triggers+=("$trigger")
  done < <(pp_javascript_trigger_names | sort -u)
  ((${#triggers[@]} == 0)) && return 0

  if [[ ! -f "${dir}/package.json" ]]; then
    local rel_trigger
    rel_trigger="$(pkg_rel_path "$path_root" "${dir}/${triggers[0]}")"
    fb_report "error" "JavaScript/TypeScript project is missing package.json beside ${triggers[0]}." "$rel_trigger" "" \
      "Add package.json beside the project config, then generate and commit exactly one supported lockfile in the same directory." "js_ts"
    return 0
  fi

  sec03_javascript_trigger_combo_allowed "$path_root" "$dir" "${triggers[@]}" || true
  sec03_validate_package_json_exact_specs "$path_root" "${dir}/package.json"

  local -a present=()
  local satisfier
  while IFS= read -r satisfier; do
    [[ -n "$satisfier" && -f "${dir}/${satisfier}" ]] && present+=("$satisfier")
  done < <(pp_javascript_satisfier_names)

  local rel
  rel="$(pkg_rel_path "$path_root" "${dir}/package.json")"
  if ((${#present[@]} == 0)); then
    fb_report "error" "JavaScript project is missing a lockfile in the package.json directory." "$rel" "" \
      "Generate and commit exactly one of package-lock.json, yarn.lock, pnpm-lock.yaml, or bun.lockb beside package.json." "js_ts"
    return 0
  fi
  if ((${#present[@]} > 1)); then
    fb_report "error" "JavaScript project has multiple lockfile families in one directory: ${present[*]}." "$rel" "" \
      "Keep exactly one package-manager lockfile family beside package.json." "js_ts"
    return 0
  fi

  local validator
  validator="$(pp_javascript_validator_for "${present[0]}")"
  cicd_sec_03_run_named_validator "$validator" "$path_root" "${dir}/${present[0]}" "javascript"
}

sec03_python_allowed_combo_sorted_space_lines() {
  local mf
  mf="$(pp_python_merged_file)"
  [[ -z "$mf" || ! -f "$mf" ]] && return 0
  if command -v yq >/dev/null 2>&1; then
    while IFS= read -r value; do
      [[ -z "$value" || "$value" == "null" ]] && continue
      python3 -c 'import json,sys; print(" ".join(sorted(json.loads(sys.argv[1]))))' "$value" 2>/dev/null || true
    done < <(yq -o=json -I=0 '(.allowed_trigger_combinations // [])[]' "$mf" 2>/dev/null || true)
  else
    printf '%s\n' "requirements.in requirements.txt" "requirements-dev.in requirements-dev.txt" "pyproject.toml requirements.txt"
  fi
}

sec03_python_trigger_combo_allowed() {
  local path_root="$1" dir="$2"
  shift 2
  local -a triggers=("$@")
  ((${#triggers[@]} <= 1)) && return 0
  local trigger_key combo allowed=false
  trigger_key="$(printf '%s\n' "${triggers[@]}" | sort -u | paste -sd' ' -)"
  while IFS= read -r combo; do
    [[ -z "$combo" ]] && continue
    [[ "$trigger_key" == "$combo" ]] && allowed=true
  done < <(sec03_python_allowed_combo_sorted_space_lines)
  $allowed && return 0

  local rel_probe
  rel_probe="$(pkg_rel_path "$path_root" "${dir}/trigger")"
  rel_probe="${rel_probe%/trigger}"
  fb_report "error" "Ambiguous Python dependency triggers in one directory; use a single trigger or a whitelisted pair." "${rel_probe}/" "" \
    "See guardrails package_policy defaults or override package_policy.python in .guardrails.file-patterns.yml." "python"
  return 1
}

sec03_validate_pip_requirements_txt_hashes() {
  local path_root="$1" abs="$2" rel
  rel="$(pkg_rel_path "$path_root" "$abs")"
  while IFS= read -r row; do
    [[ -z "$row" ]] && continue
    if [[ "$row" == UNPINNED\|* ]]; then
      local rest ln content
      rest="${row#UNPINNED|}"
      ln="${rest%%|*}"
      content="${rest#*|}"
      fb_report "error" "Unpinned python dependency '${content}'." "$rel" "$ln" \
        "Pin each dependency with exact == version and pip --hash lines (pip-compile --generate-hashes)." "python"
    elif [[ "$row" == MISSING_HASH\|* ]]; then
      local rest pkg ln
      rest="${row#MISSING_HASH|}"
      ln="${rest%%|*}"
      pkg="${rest#*|}"
      fb_report "error" "Python requirement is pinned but missing a pip --hash= line for '${pkg}'." "$rel" "$ln" \
        "Regenerate with pip-compile --generate-hashes (or equivalent) and commit the lock output." "python"
    fi
  done < <(
    python3 - "$abs" <<'PY'
import re
import sys

raw_lines = open(sys.argv[1], encoding="utf-8", errors="replace").read().splitlines()
events = []
for phys_ln, line in enumerate(raw_lines, start=1):
    s = line.strip()
    if not s or s.startswith("#") or s.startswith(("-r ", "-c ", "-i ", "--")):
        continue
    if "==" not in line:
        events.append((phys_ln, 0, "UNPINNED", s))


def logical_blocks(raw):
    out = []
    for lineno, line in enumerate(raw, start=1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        s = line.rstrip("\n")
        if out and out[-1][1].rstrip().endswith("\\"):
            prev_ln, prev_text = out[-1]
            out[-1] = (prev_ln, prev_text.rstrip().rstrip("\\").rstrip() + " " + s.lstrip())
        else:
            out.append((lineno, s))
    return out


def is_skipped(text):
    text = text.lstrip()
    if text.startswith(("-r ", "-c ", "--", "-i ", "-e ")):
        return True
    return text.startswith("-") and not re.match(r"^[A-Za-z0-9_.+\[\]-]+==", text)


def is_requirement(text):
    text = text.lstrip()
    return bool(text and not text.startswith("#") and not is_skipped(text) and
                re.match(r"^[A-Za-z0-9_.+\[\]-]+(?:==|>=|<=|~=|!=|>|<|@)", text))


for start_ln, block in logical_blocks(raw_lines):
    block = block.strip()
    if not block or is_skipped(block) or not is_requirement(block):
        continue
    if "--hash=" not in block and " --hash=" not in block:
        package = block.split()[0] if block.split() else block
        events.append((start_ln, 1, "MISSING_HASH", package))

for line, _priority, kind, payload in sorted(events, key=lambda item: (item[0], item[1])):
    print(f"{kind}|{line}|{payload}")
PY
  )
}

sec03_validate_poetry_lock_hashes() {
  local path_root="$1" abs="$2" rel error
  rel="$(pkg_rel_path "$path_root" "$abs")"
  error="$(
    python3 - "$abs" <<'PY'
import sys

text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
if "[metadata]" not in text or "content-hash" not in text:
    print("missing_lock_metadata")
elif "[[package]]" not in text:
    print("no_packages")
else:
    for index, block in enumerate(text.split("[[package]]")[1:], start=1):
        if "sha256" not in block and "sha512" not in block and "hash =" not in block:
            print(f"package_without_hash:{index}")
            break
PY
  )"
  [[ -z "$error" ]] && return 0
  case "$error" in
    missing_lock_metadata)
      fb_report "error" "poetry.lock is missing metadata content-hash (invalid or stale lock)." "$rel" "" \
        "Run poetry lock and commit poetry.lock." "python"
      ;;
    no_packages)
      fb_report "error" "poetry.lock contains no [[package]] entries." "$rel" "" \
        "Run poetry lock and commit poetry.lock." "python"
      ;;
    package_without_hash:*)
      fb_report "error" "poetry.lock has a package block without integrity hash evidence." "$rel" "" \
        "Regenerate poetry.lock with a current Poetry version and commit." "python"
      ;;
  esac
}

sec03_validate_uv_lock_hashes() {
  local path_root="$1" abs="$2" rel error
  rel="$(pkg_rel_path "$path_root" "$abs")"
  error="$(
    python3 - "$abs" <<'PY'
import re
import sys

text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
if "[[package]]" not in text:
    print("no_packages")
else:
    digest = re.compile(r"sha256-[0-9a-fA-F]{64}")
    for index, block in enumerate(text.split("[[package]]")[1:], start=1):
        if not digest.search(block):
            print(f"package_without_digest:{index}")
            break
PY
  )"
  [[ -z "$error" ]] && return 0
  case "$error" in
    no_packages)
      fb_report "error" "uv.lock contains no [[package]] entries." "$rel" "" \
        "Run uv lock and commit uv.lock." "python"
      ;;
    package_without_digest:*)
      fb_report "error" "uv.lock has a package block without a sha256 digest." "$rel" "" \
        "Run uv lock and commit uv.lock." "python"
      ;;
  esac
}

cicd_sec_03_run_python_package_policy() {
  local path_root="$1"
  shift
  local -a inventory_triggers=("$@")
  local -a satisfiers=()
  local item
  while IFS= read -r item; do
    [[ -n "$item" ]] && satisfiers+=("$item")
  done < <(pp_python_satisfier_names)

  local -a directories=()
  while IFS= read -r item; do
    [[ -n "$item" ]] && directories+=("$item")
  done < <(
    local artifact rel
    for artifact in "${inventory_triggers[@]+"${inventory_triggers[@]}"}"; do
      [[ -z "$artifact" || ! -f "$artifact" ]] && continue
      rel="$(pkg_rel_path "$path_root" "$artifact")"
      fp_should_skip_validation "$rel" && continue
      dirname "$artifact"
    done | sort -u
  )

  local dir
  for dir in "${directories[@]+"${directories[@]}"}"; do
    local -a triggers=()
    while IFS= read -r item; do
      [[ -n "$item" && -f "${dir}/${item}" ]] && triggers+=("$item")
    done < <(pp_python_trigger_names | sort -u)
    ((${#triggers[@]} == 0)) && continue
    sec03_python_trigger_combo_allowed "$path_root" "$dir" "${triggers[@]}" || true

    local found=false
    for item in "${satisfiers[@]+"${satisfiers[@]}"}"; do
      [[ -f "${dir}/${item}" ]] && found=true
    done
    if ! $found && ((${#satisfiers[@]} > 0)); then
      local rel_dir
      rel_dir="$(pkg_rel_path "$path_root" "${dir}/${triggers[0]}")"
      rel_dir="${rel_dir%/*}"
      fb_report "error" "Python project directory is missing a required lock or hashed requirements file." "${rel_dir}/" "" \
        "Add one of the configured satisfier files next to the trigger manifest (see package_policy defaults)." "python"
    fi

    for item in "${satisfiers[@]+"${satisfiers[@]}"}"; do
      [[ -f "${dir}/${item}" ]] || continue
      local rel validator
      rel="$(pkg_rel_path "$path_root" "${dir}/${item}")"
      fp_should_skip_validation "$rel" && continue
      validator="$(pp_python_validator_for "$item")"
      [[ -z "$validator" ]] && continue
      cicd_sec_03_run_named_validator "$validator" "$path_root" "${dir}/${item}" "python"
    done
  done

  local count="${#directories[@]}" satisfier_desc sample="" limit seen=0
  if ((${#satisfiers[@]} > 0)); then
    satisfier_desc="$(printf '%s, ' "${satisfiers[@]}")"
    satisfier_desc="${satisfier_desc%, }"
  else
    satisfier_desc="(none configured)"
  fi
  limit="$(fb_coverage_path_sample_limit)"
  for dir in "${directories[@]+"${directories[@]}"}"; do
    seen=$((seen + 1))
    [[ $seen -gt $limit ]] && break
    item="$(pkg_rel_path "$path_root" "$dir")"
    sample="${sample:+$sample; }${item}/"
  done
  local more=""
  [[ $count -gt $limit ]] && more=" (+$((count - limit)) more directories)"
  if [[ $count -eq 0 ]]; then
    fb_add_coverage "Python package_policy: no directories with trigger files after applying repository validation rules."
  else
    fb_add_coverage "Python package_policy: ${count} director(ies) with triggers; satisfiers: ${satisfier_desc}${sample:+; sample: }${sample}${more}"
  fi
}
